### ISSUE TITLE
Heap Allocation ?

### ISSUE THREAD

**Issue by Dathuss** [numworks/epsilon-sample-app-cpp#12]
Hey. I don't really understand how heap allocation is supported on epsilon, because I'm aware the function `eadk_heap_range(uint32_t* start, uint32_t* end)` exists but how exactly do I know what values to pass without overwriting important data, and most of all, the `new` operator seems to be unavailable, so it brings me to ask, how exactly am I supposed to store chunks of data the stack cannot handle ? Thanks for your answer.

**Comment by Ecco** [comment]
That's a very good question. Note how the `start` and `end` parameters are actually *pointers*. Because a C function can only have one return value, this is a commonly used way to return more than one value from a C function. You should use it like this:
```c
uint32_t heapStart; // Uninitialized
uint32_t heapEnd; // Uninitialized
eadk_heap_range(&heapStart, &heapEnd);
// At this point, you can use the area between heapStart and heapEnd as a heap
```

In other words, you don't need to come up with values for `heapStart` or `heapEnd`: they are *output* values from `eadk_heap_range`.

Now, we do not (yet?) provide an implementation of `malloc` (or `new` for that matter) so you will have to implement your own allocator. But at least the syscall tells you about a memory location you can safely use.

**Comment by RedGl0w** [comment]
> That's a very good question. Note how the `start` and `end` parameters are actually _pointers_.

By the way, shouldn't they be `void**` ? This would look way more natural, because storing addresses in `uint32_t` doens't look like a very common way to store them.

**Comment by Ecco** [comment]
Yeah, you're right! That being said, we are actually considering replacing this syscall with something else.

We want to let 3rd-party apps use some heap memory. But we don't really know how much heap memory we will be able to offer across different versions of Epsilon. Initially we considered several options:
1. Use a convention. For example, we could say we will always ensure zone `0x20002000-0x20002FFF` is useable by 3rd-party apps.
2. Use a syscall to dynamically let 3rd-party apps know what RAM they can use.

Option 2 seems like the only reasonable solution. Indeed, for option 1 either we would commit to a super tiny zone, or risk preventing future versions of Epsilon from doing "cool stuff" because we had committed to too big of an area before.

But after thinking about this, Option 2 kind of sucks too. Because you can't know at compile-time where the useable RAM is going to be, then you have to write PIC code, and, more importantly, relocate your code. Which is a giant pain in the butt (and also somewhat comes with a runtime performance penalty).

But actually, we *already* had a similar problem when *writing* apps in Flash memory. You can't really know where your program is going to be because there can be more than one 3rd-party app. So when you want to upload your app to your calculator, you need to first read the calculator's memory from the host, and then write the app at the appropriate location. That's an approach we've used quite a lot in the past (i.e. make the host PC do the heavy lifting), and that has proven to be a really good decision.

So, introducing Option 3. We take a *convention* of a location somewhere in the Flash memory. This location will contain two pointers that delimit the usable RAM memory that a 3rd party app can use. This *location* will stay the same across versions of Epsilon, but the *values* at that location will change.

Then to run a 3rd-party app, we would then need to do the following steps:
1. Just like before, peek the calculator's memory over DFU and figure out where the app will need to be written in Flash
2. Keep on peeking, and also read what RAM zone the app will be able to use
3. Link the 3rd-party app using these 3 addresses
4. Write the 3rd-party app using DFU

In practice, this means that apps will need to be re-linked from the host before being run. But that's probably easier to do, and it is definitely more efficient when running the app. In other words, some form of "dynamic" linking is required, and we might as well just do it on the host.

**Comment by RedGl0w** [comment]
> In practice, this means that apps will need to be re-linked from the host before being run. But that's probably easier to do, and it is definitely more efficient when running the app. In other words, some form of "dynamic" linking is required, and we might as well just do it on the host.

So, we would be doing somehow how @zardam has been doing in his [external apps system](https://github.com/zardam/nw-external-apps), by having a linker in browser ? Fist time I took a look at that, and when I understood how it [worked](https://github.com/zardam/nw-external-apps/blob/master/index.js#L55-L76), I realized that even if it works pretty well, it looks like a very *quick* but pretty *dirty* solution : apps can't be deleted without having to relink all apps after it, it can be sometime a bit slow to run in a browser, ...
I don't think Option 2 would be a perfect, but it could introduce some other pretty convenient solution : why not having somehow an OS similar userland for the apps : for instance, the epsilon userland could be installed with at first position in the apps slots a dynamic relocator (which would be compiled for this epsilon userland), which could be found in a lot of FOSS project, which would be called pretty easily from the other apps installed, with a minimal performance impact (relocation should only be done theoricaly at first load of the app at this address), and in the future bring solution for dynamic linker.
It shouldn't be a pain in the butt, because most of the complex part is done in another part, which wouldn't need to be real PIC (which is the main part of the pain), without real security issue (the relocation is done in supervised mode, like other app could do it).
